services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: sh -c "
      sleep 5 &&
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
      - POSTGRES_HOST=db
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"


#  shell:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: shell
#    command: tail -f /dev/null
#    depends_on:
#      - db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres_db
#      - POSTGRES_HOST=db
#    volumes:
#      - .:/app


  run_test_script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: run_test_script
    command:
      sh -c "
      sleep 10 &&
      python ./run_tests.py"
    depends_on:
      - db
      - app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
      - POSTGRES_HOST=db
