services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: /bin/sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
      - POSTGRES_HOST=db
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  shell:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shell
    command: tail -f /dev/null
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
      - POSTGRES_HOST=db
    volumes:
      - .:/app


  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    command: python ./test_script.py
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
      - POSTGRES_HOST=db


volumes:
  db_data:
