"""Add unique constraint to books

Revision ID: 897846b42f3e
Revises: a92646f5eec4
Create Date: 2025-08-07 16:36:20.168284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897846b42f3e'
down_revision: Union[str, None] = 'a92646f5eec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_books_pages'), 'books', ['pages'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_unique_constraint('uq_title_author', 'books', ['title', 'author'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_title_author', 'books', type_='unique')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_pages'), table_name='books')
    # ### end Alembic commands ###
